global:
  resolve_timeout: 5m

route:
  receiver: 'team-notifications'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'team-notifications'
    email_configs:
      - to: 'devops@stellarbridge.finance'
        from: 'alertmanager@stellarbridge.finance'
        smarthost: 'smtp.mailserver.com:587'
        auth_username: 'alertmanager'
        auth_identity: 'alertmanager@example.com'
        auth_password: 'yourpassword'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal:
      - alertname
      - cluster
