/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IResolver {
  export type ResolverInfoStruct = {
    stake: BigNumberish;
    reputation: BigNumberish;
    totalVolume: BigNumberish;
    successRate: BigNumberish;
    avgResponseTime: BigNumberish;
    active: boolean;
    registrationTime: BigNumberish;
  };

  export type ResolverInfoStructOutput = [
    stake: bigint,
    reputation: bigint,
    totalVolume: bigint,
    successRate: bigint,
    avgResponseTime: bigint,
    active: boolean,
    registrationTime: bigint
  ] & {
    stake: bigint;
    reputation: bigint;
    totalVolume: bigint;
    successRate: bigint;
    avgResponseTime: bigint;
    active: boolean;
    registrationTime: bigint;
  };
}

export interface ResolverRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SLASHING"
      | "MIN_STAKE"
      | "REPUTATION_DECAY_PERIOD"
      | "activeResolvers"
      | "getActiveResolverCount"
      | "getResolverInfo"
      | "getTopResolvers"
      | "isActiveResolver"
      | "owner"
      | "pause"
      | "paused"
      | "registerResolver"
      | "renounceOwnership"
      | "resolverSlashings"
      | "resolverStakes"
      | "resolvers"
      | "slashResolver"
      | "totalSlashed"
      | "totalStaked"
      | "transferOwnership"
      | "unpause"
      | "updateReputation"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "ResolverRegistered"
      | "ResolverSlashed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_SLASHING",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_DECAY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeResolvers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveResolverCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResolverInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopResolvers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerResolver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolverSlashings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolverStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashResolver",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSlashed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_SLASHING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_DECAY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveResolverCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolverInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverSlashings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolvers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSlashed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    resolver: AddressLike,
    oldReputation: BigNumberish,
    newReputation: BigNumberish
  ];
  export type OutputTuple = [
    resolver: string,
    oldReputation: bigint,
    newReputation: bigint
  ];
  export interface OutputObject {
    resolver: string;
    oldReputation: bigint;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverRegisteredEvent {
  export type InputTuple = [
    resolver: AddressLike,
    stake: BigNumberish,
    reputation: BigNumberish
  ];
  export type OutputTuple = [
    resolver: string,
    stake: bigint,
    reputation: bigint
  ];
  export interface OutputObject {
    resolver: string;
    stake: bigint;
    reputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverSlashedEvent {
  export type InputTuple = [
    resolver: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [resolver: string, amount: bigint, reason: string];
  export interface OutputObject {
    resolver: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ResolverRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ResolverRegistry;
  waitForDeployment(): Promise<this>;

  interface: ResolverRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SLASHING: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_DECAY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  activeResolvers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getActiveResolverCount: TypedContractMethod<[], [bigint], "view">;

  getResolverInfo: TypedContractMethod<
    [resolver: AddressLike],
    [IResolver.ResolverInfoStructOutput],
    "view"
  >;

  getTopResolvers: TypedContractMethod<
    [count: BigNumberish],
    [string[]],
    "view"
  >;

  isActiveResolver: TypedContractMethod<
    [resolver: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerResolver: TypedContractMethod<
    [minStake: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolverSlashings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  resolverStakes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  resolvers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stake: bigint;
        reputation: bigint;
        totalVolume: bigint;
        successRate: bigint;
        avgResponseTime: bigint;
        active: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  slashResolver: TypedContractMethod<
    [resolver: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  totalSlashed: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateReputation: TypedContractMethod<
    [resolver: AddressLike, success: boolean, responseTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SLASHING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_DECAY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeResolvers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveResolverCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResolverInfo"
  ): TypedContractMethod<
    [resolver: AddressLike],
    [IResolver.ResolverInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopResolvers"
  ): TypedContractMethod<[count: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "isActiveResolver"
  ): TypedContractMethod<[resolver: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerResolver"
  ): TypedContractMethod<[minStake: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolverSlashings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolverStakes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolvers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stake: bigint;
        reputation: bigint;
        totalVolume: bigint;
        successRate: bigint;
        avgResponseTime: bigint;
        active: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "slashResolver"
  ): TypedContractMethod<
    [resolver: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalSlashed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [resolver: AddressLike, success: boolean, responseTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverRegistered"
  ): TypedContractEvent<
    ResolverRegisteredEvent.InputTuple,
    ResolverRegisteredEvent.OutputTuple,
    ResolverRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ResolverSlashed"
  ): TypedContractEvent<
    ResolverSlashedEvent.InputTuple,
    ResolverSlashedEvent.OutputTuple,
    ResolverSlashedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "ResolverRegistered(address,uint256,uint256)": TypedContractEvent<
      ResolverRegisteredEvent.InputTuple,
      ResolverRegisteredEvent.OutputTuple,
      ResolverRegisteredEvent.OutputObject
    >;
    ResolverRegistered: TypedContractEvent<
      ResolverRegisteredEvent.InputTuple,
      ResolverRegisteredEvent.OutputTuple,
      ResolverRegisteredEvent.OutputObject
    >;

    "ResolverSlashed(address,uint256,string)": TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;
    ResolverSlashed: TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
