/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStellarBridge,
  IStellarBridgeInterface,
} from "../../../contracts/interfaces/IStellarBridge";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "SwapInitiated",
    type: "event",
  },
] as const;

export class IStellarBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IStellarBridgeInterface {
    return new Interface(_abi) as IStellarBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStellarBridge {
    return new Contract(address, _abi, runner) as unknown as IStellarBridge;
  }
}
