/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPartialFill {
  export type FillOrderStruct = {
    swapId: BytesLike;
    resolver: AddressLike;
    amount: BigNumberish;
    bidPrice: BigNumberish;
    timestamp: BigNumberish;
    merkleRoot: BytesLike;
    executed: boolean;
  };

  export type FillOrderStructOutput = [
    swapId: string,
    resolver: string,
    amount: bigint,
    bidPrice: bigint,
    timestamp: bigint,
    merkleRoot: string,
    executed: boolean
  ] & {
    swapId: string;
    resolver: string;
    amount: bigint;
    bidPrice: bigint;
    timestamp: bigint;
    merkleRoot: string;
    executed: boolean;
  };
}

export interface IPartialFillInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeFillOrders"
      | "getCurrentPrice"
      | "getFillOrders"
      | "placeBid"
      | "startAuction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuctionStarted" | "BidPlaced" | "FillOrderExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeFillOrders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFillOrders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "startAuction",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeFillOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFillOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startAuction",
    data: BytesLike
  ): Result;
}

export namespace AuctionStartedEvent {
  export type InputTuple = [
    swapId: BytesLike,
    startPrice: BigNumberish,
    reservePrice: BigNumberish
  ];
  export type OutputTuple = [
    swapId: string,
    startPrice: bigint,
    reservePrice: bigint
  ];
  export interface OutputObject {
    swapId: string;
    startPrice: bigint;
    reservePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    swapId: BytesLike,
    resolver: AddressLike,
    bidPrice: BigNumberish
  ];
  export type OutputTuple = [
    swapId: string,
    resolver: string,
    bidPrice: bigint
  ];
  export interface OutputObject {
    swapId: string;
    resolver: string;
    bidPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FillOrderExecutedEvent {
  export type InputTuple = [
    swapId: BytesLike,
    resolver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [swapId: string, resolver: string, amount: bigint];
  export interface OutputObject {
    swapId: string;
    resolver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPartialFill extends BaseContract {
  connect(runner?: ContractRunner | null): IPartialFill;
  waitForDeployment(): Promise<this>;

  interface: IPartialFillInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeFillOrders: TypedContractMethod<
    [swapId: BytesLike],
    [void],
    "nonpayable"
  >;

  getCurrentPrice: TypedContractMethod<[swapId: BytesLike], [bigint], "view">;

  getFillOrders: TypedContractMethod<
    [swapId: BytesLike],
    [IPartialFill.FillOrderStructOutput[]],
    "view"
  >;

  placeBid: TypedContractMethod<
    [
      swapId: BytesLike,
      bidPrice: BigNumberish,
      fillAmount: BigNumberish,
      merkleProof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  startAuction: TypedContractMethod<
    [swapId: BytesLike, startPrice: BigNumberish, reservePrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeFillOrders"
  ): TypedContractMethod<[swapId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[swapId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFillOrders"
  ): TypedContractMethod<
    [swapId: BytesLike],
    [IPartialFill.FillOrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [
      swapId: BytesLike,
      bidPrice: BigNumberish,
      fillAmount: BigNumberish,
      merkleProof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startAuction"
  ): TypedContractMethod<
    [swapId: BytesLike, startPrice: BigNumberish, reservePrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionStarted"
  ): TypedContractEvent<
    AuctionStartedEvent.InputTuple,
    AuctionStartedEvent.OutputTuple,
    AuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "FillOrderExecuted"
  ): TypedContractEvent<
    FillOrderExecutedEvent.InputTuple,
    FillOrderExecutedEvent.OutputTuple,
    FillOrderExecutedEvent.OutputObject
  >;

  filters: {
    "AuctionStarted(bytes32,uint256,uint256)": TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;
    AuctionStarted: TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;

    "BidPlaced(bytes32,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "FillOrderExecuted(bytes32,address,uint256)": TypedContractEvent<
      FillOrderExecutedEvent.InputTuple,
      FillOrderExecutedEvent.OutputTuple,
      FillOrderExecutedEvent.OutputObject
    >;
    FillOrderExecuted: TypedContractEvent<
      FillOrderExecutedEvent.InputTuple,
      FillOrderExecutedEvent.OutputTuple,
      FillOrderExecutedEvent.OutputObject
    >;
  };
}
